FitMax.Mvc/Controllers/UserPageController.cs
using FitMax.Entity.IService;
using FitMax.Entity.ViewModels;
using FitMax.Service.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitMax.Mvc.Controllers
{
    [Authorize]
    public class UserPageController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ICartService _cartService;
        private readonly IPrivateLessonService _privateLessonService;
        private readonly ICartLineService _cartLineService;
        private readonly IPackageService _packageService;   

        public UserPageController(IAccountService accountService, ICartService cartService, IPrivateLessonService privateLessonService, ICartLineService cartLineService, IPackageService packageService)
        {
            _accountService = accountService;
            _cartService = cartService;
            _privateLessonService = privateLessonService;
            _cartLineService = cartLineService;
            _packageService = packageService;
        }

        public async Task<IActionResult> StudentOrTrainer()
        {
            string userName = User.Identity.Name;
            UserViewModel user = await _accountService.GetUserByNameAsync(userName);

            if (user != null)
            {
                if (user.UserType == "Eğitmen")
                {
                    return RedirectToAction("TrainerIndex", new { userName = userName });
                }
                else
                {
                    return RedirectToAction("Index", new { userName = userName });
                }
            }

            return NotFound();
        }


        public async Task<IActionResult> Index(string userName)
        {
            var user= await _accountService.GetUserByNameAsync(userName);
            DeliveryListViewModel delivery=await _cartService.GetCartById(user.Id);
            ViewBag.deliveryFalse = delivery.IsFalse;
            ViewBag.deliveryTrue= delivery.IsTrue;

            UserLessonListViewModel lessons = await _privateLessonService.GetUserLessons(user.Id);
            ViewBag.lessonFalse = lessons.IsFalse;
            ViewBag.lessonTrue = lessons.IsTrue;

            //Paket Adını getirme
            PackageViewModel packageViewModel = await _packageService.GetByPackage(Convert.ToInt32(user.Package));
            ViewBag.package = packageViewModel.Name;

            return View(await _accountService.GetUserByIdAsync(user.Id));
        }
        public async Task<IActionResult> TrainerIndex(string userName)
        {
            var trainer = await _accountService.GetUserByNameAsync(userName);
            UserLessonListViewModel lessons = await _privateLessonService.GetTrainerLessons(trainer.Id);
            ViewBag.lessonFalse = lessons.IsFalse;
            ViewBag.lessonTrue = lessons.IsTrue;
            DeliveryListViewModel delivery = await _cartService.GetCartById(trainer.Id);
            ViewBag.deliveryFalse = delivery.IsFalse;
            ViewBag.deliveryTrue = delivery.IsTrue;

            return View(await _accountService.GetUserByIdAsync(trainer.Id));

        }
        [HttpPost]
        public async Task<IActionResult> UpdateUserInfo(UserViewModel model, IFormFile formFile)
        {
            if (formFile != null)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", formFile.FileName);
                var stream = new FileStream(path, FileMode.Create);
                formFile.CopyTo(stream);
                model.ImgUrl = "/images/" + formFile.FileName;
            }
             await _accountService.UpdateInfo(model);


            await _accountService.UpdateInfo(model);
            {
                if (model.UserType != "Üye")
                {
                    return RedirectToAction("TrainerIndex", new { userName = model.UserName });
                }
                else
                {
                    return RedirectToAction("Index", new { userName = model.UserName });
                }
            }

        }   
        public async Task<IActionResult> UserCartLines(int id)
        {
            var model = await _cartLineService.GetCartLineByCartId(id);
            return View(model);

        }
        public async Task<IActionResult> LessonDescription(int id)
        {

            return View(await _privateLessonService.GetLessonDetails(id));
        }
        [HttpPost]
        public async Task<IActionResult> LessonDescription(PrivateLessonViewModel model)
        {
            _privateLessonService.UpdateLessonDetails(model);


            return View(model);
        }

    }
}

FitMax.Mvc/Views/UserPage/Index.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<section class="s-news" style="margin:-130px">
    <div class="container">
        <div class="row">
            <div class="col-6 col-lg-6 ">
                <div class="post-item-cover">
                    <div class="post-header">
                        <div class="post-thumbnail">
                            <img src="~/fitmax/assets/img/blog-1.jpg" alt="img" class="img-fluid rounded float-left" width="100px">
                        </div>
                    </div>
                </div>
            </div>

            <!--Hidayet boy kilo ve paket güncelleme-->
            <div class="col-6 col-lg-6 ">


                <div class="row mb-3 justify-content-center">
                    <h3 class="text-center">Paket Bilgilerim</h3>
                </div>
                @if (Model.Package == null)
                {
                    <h4>AKTİF BİR ÜYELİĞİNİZ BULUNMAMAKTADIR: PAKET ALMAK İÇİN TIKLAYINIZ</h4>
                }
                else
                {
                    <div class="row">
                        <div class="container">

                            <div class="row">
                                <div class="col mb-3">
                                    <label for="">Paket:</label>
                                </div>
                                <div class="col">
                                    <input type="text" value="@ViewBag.package" readonly class="form-control">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="">Başlangıç Tarihi</label>
                                </div>
                                <div class="col">
                                    <input type="text" value="@Model.PackageStartDate" readonly class="form-control">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="">Bitiş Tarihi</label>
                                </div>
                                <div class="col">
                                    <input type="text" value="@Model.PackageEndDate" readonly class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                }




                <!--    Kullanıcı Boy ve Kilo Bilgisi      -->
                <form method="post" asp-controller="UserPage" asp-action="UpdateUserInfo">
                    <input type="hidden" asp-for="UserType" value=@Model.UserType />
                    <input type="hidden" asp-for="Id" value=@Model.Id />
                    <input asp-for="UserName" value="@User.Identity.Name" type="hidden" />
                    <div class="row">
                        <div class="container">
                            <div class="row mb-3 justify-content-center">
                                <h3 class="text-center">Fiziksel Özellikler</h3>
                            </div>
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="">Boy Bilgisi:</label>
                                </div>
                                <div class="col">
                                    <input asp-for=Height type="text" value="@Model.Height">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="">Kilo Bilgisi</label>
                                </div>
                                <div class="col">
                                    <input asp-for="Weight" type="text" value="@Model.Weight">
                                </div>
                            </div>
                            <div class="row mt-5 bg-light justify-content-center">
                                <div>
                                    <Button type="submit" class="btn">Boy ve Kilo Bilgilerinizi Güncelleyin.</Button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </div>
        <div class="container">
            <div class="row">

                <div class="col-7 col-lg-7 ">


                    <div class="col-lg-12  ">
                        <div class="">
                            <div class="card-body">
                                <div class="mb-2" style="text-align:center!important; background-color:gray">
                                <h4 class="card-title">Teslim Edilmeyen Siparişler</h4>
                                </div>
                                <div class="table-responsive" style="overflow-y: auto; max-height: 300px;">
                                    <table class="training-schedule-table">
                                        <thead>

                                            <tr>

                                                <th> Sipariş Tarihi </th>

                                                <th> Tutar </th>
                                                <th> Detaylar </th>

                                            </tr>
                                        </thead>
                                      
                                        <tbody>

                                            @foreach (var item in ViewBag.deliveryFalse)
                                                {
                                                    <tr>
                                                        <td> @item.OrderDate </td>
                                                        <td> @item.TotalPrice.ToString("C") </td>
                                                        <td>
                                                            @if (!item.Status)
                                                            {
                                                            <a class="btn btn-success" asp-controller="UserPage" asp-action="UserCartLines" asp-route-id="@item.Id">Detay</a>
                                                            }
                                                        </td>
                                                    </tr>
                                                
                                            }
                                         
                                        </tbody>


                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 grid-margin stretch-card">
                        <div class="">
                            <div class="card-body">
                                <div class="mb-2" style="text-align:center!important;background-color:gray">
                                <h4 class="card-title">Teslim Edilen Siparişler</h4>
                                </div>
                                <div class="table-responsive" style="overflow-y: auto; max-height: 300px;">
                                    <table class="training-schedule-table">
                                        <thead>
                                            <tr>


                                                <th> Sipariş Tarihi </th>
                                                <th> Teslim Tarihi </th>
                                                <th> Tutar </th>
                                                <th> Detaylar </th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in ViewBag.deliveryTrue)
                                            {

                                                <tr>

                                                    <td> @item.OrderDate </td>
                                                    <td> @item.DeliveryDate </td>
                                                    <td> @item.TotalPrice.ToString("C") </td>

                                                    <td>

                                                        <a class="btn btn-success" asp-controller="UserPage" asp-action="UserCartLines" asp-route-id="@item.Id">Detay</a>

                                                    </td>

                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="col-5 col-lg-5 ">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="">
                                <div class="card-body">
                                    <div class="mb-2" style="text-align:center!important;background-color:gray">
                                    <h4 class="card-title">Gelecek Özel Dersler</h4>
                                    </div>
                                    <div class="table-responsive" style="overflow-y: auto; max-height: 300px;">
                                        <table class="training-schedule-table">
                                            <thead>
                                                <tr>


                                                    <th> Ders Tarihi </th>
                                                    <th> Eğitmen </th>


                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in ViewBag.lessonTrue)
                                                {

                                                    <tr>

                                                        <td> @item.Date </td>
                                                        <td> @item.TrainerName </td>


                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!---->
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="">
                                <div class="card-body">
                                    <div class="mb-2" style="text-align:center!important;background-color:gray">
                                    <h4 class="card-title">Geçmiş Özel Dersler</h4>
                                    </div>
                                    <div class="table-responsive" style="overflow-y: auto; max-height: 300px;">
                                        <table class="training-schedule-table">
                                            <thead>
                                                <tr>


                                                    <th> Ders Tarihi </th>
                                                    <th> Eğitmen </th>


                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in ViewBag.lessonFalse)
                                                {

                                                    <tr>

                                                        <td> @item.Date </td>
                                                        <td> @item.TrainerName </td>


                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>


            </div>

        </div>
        <tr>
            <td>

                <a asp-controller="Account" asp-action="PasswordNewNormal" class="btn">Şifre Değiştir</a>
            </td>
        </tr>

    </div>
</section>
<!--=================== S-NEWS END ===================-->

FitMax.Mvc/Views/UserPage/LessonDescription.cshtml
@model PrivateLessonViewModel
@{
    ViewData["Title"] = "LessonDescription";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h1> </h1>
<div>
    <form method="post" asp-action="LessonDescription" asp-controller="UserPage" enctype="multipart/form-data">

        <input asp-for="Id" value="@Model.Id" type="hidden" />


        <div class="container">
            <div class="row">

                <div class="col-12 col-lg-12 ">
                    <div class="btn-form-cover">

                        <a asp-controller="UserPage" asp-action="StudentOrTrainer" asp-route-userName="@User.Identity.Name" class="btn">Geri</a>
                    </div>

                    <div class="">
                        <div class="training-schedule-table">
                            <h4 class="card-title">@Model.Lesson</h4>
                            <div class="table-responsive">

                                <table class="table">

                                    <tbody>
                                        <tr>
                                            <td>Dersin Tarihi</td>
                                            <td>@Model.Date</td>
                                        </tr>

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12  ">
                    <div class="">
                        <div class="training-schedule-table">
                            <h4 class="card-title">Dersin Açıklaması</h4>
                            <div class="table-responsive">

                                <table class="table">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <input asp-for="Description" value="@Model.Description" type="text" class="form-control" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <button class="btn" type="submit">Güncelle</button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>

FitMax.Mvc/Views/UserPage/UserCartLines.cshtml
@model IEnumerable<CartLineViewModel>
@{
    ViewData["Title"] = "UserCartLines";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="container" id="Tablo">
    <div class="row">

        <div class="col-2 ">
            <h1>Sepet</h1>
        </div>
        <div class="col-8"></div>
        <div class="col-2 mt-4">
        </div>
    </div>
    <table class="training-schedule-table">
        <thead>
            <tr>
                <th>Ürün Adı</th>
                <th>Adet</th>
                <th>Birim Fiyat</th>
                <th>Toplam</th>
                <th>Spariş Tarihi</th>
                <th>Teslim Tarihi</th>
                


            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                decimal total = 0;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Product.Name</td>                

                        <td>
                            <p style="width:5px; display:inline-block"><strong>@item.Quantity</strong></p>
                        </td>

                        <td>@item.UnitPrice.ToString("C")</td>
                        <td style="width:150px">@((item.UnitPrice * item.Quantity).ToString("C")) </td>
                        <td>@item.OrderDate</td>
                        <td>@item.DeliveryDate</td>


                    </tr>
                    total = total + item.UnitPrice * item.Quantity;
                }

                <tr>
                    <td colspan="4"></td> <!-- Boş hücreler ekleyin -->
                    <td style="text-align: center;">
                        Sepet Toplam:

                    </td>
                    <td>
                        @total.ToString("C")

                </tr>

            }
        </tbody>
    </table>




</div>