FitMax.Mvc/Controllers/CartController.cs
using FitMax.Entity.Entities;
using FitMax.Entity.IService;
using FitMax.Entity.ViewModels;
using FitMax.Mvc.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using System.Security.Claims;

namespace FitMax.Mvc.Controllers

{
    public class CartController : Controller
    {
        private readonly IWalletService _walletService;
        private readonly IWalletDetailService _walletDetailService;
        private readonly IPackageService _packageService;
        private readonly IAccountService _accountService;
        private readonly IPrivateLessonService _lessonService;
        private readonly IProductService _productService;
        private readonly ICartLineService _cartLineService;
        private readonly ICartService _cartService;



        public CartController(IWalletService walletService, IWalletDetailService walletDetailService, IPackageService packageService, IAccountService accountService, IPrivateLessonService lessonService, ICartLineService cartLineService, IProductService productService, ICartService cartService)
        {
            _walletService = walletService;
            _walletDetailService = walletDetailService;
            _packageService = packageService;
            _accountService = accountService;
            _lessonService = lessonService;
            _cartLineService = cartLineService;
            _productService = productService;
            _cartService = cartService;

        }

        List<CartLineViewModel> cart;


        public IActionResult Index()
        {
            cart = TakeCart();
            return View(cart);
        }
        public List<CartLineViewModel> TakeCart()
        {
            var cart = HttpContext.Session.GetJson<List<CartLineViewModel>>("cart") ?? new List<CartLineViewModel>();
            return cart;
        }

        public int AddInCart(int Id)
        {
            ProductViewModel product = _productService.GetById(Id);
            cart = TakeCart();
            if (cart.FirstOrDefault(x => x.ProductId == product.Id) != null)
            {                


                if (cart.FirstOrDefault(x => x.ProductId == product.Id).Quantity < product.Stock)
                {
                    CartLineViewModel cartline = new CartLineViewModel();
                    cartline.ProductId = product.Id;
                    cartline.CartId = 0;
                    cartline.Quantity = 1;
                    cartline.UnitPrice = product.Price;
                    cartline.TotalPrice = (cart.FirstOrDefault(x => x.ProductId == product.Id).Quantity+1) * product.Price;
                    cartline.Name = product.Name;
                    cart = _cartLineService.AddToCart(cart, cartline);
                    SaveCart(cart);

                    return cart.Count();

                }
                else
                {
                    return 5000;
                }
            }
            else
            {
                CartLineViewModel cartline = new CartLineViewModel();
                cartline.ProductId = product.Id;
                cartline.CartId = 0;
                cartline.Quantity = 1;
                cartline.UnitPrice = product.Price;
                cartline.TotalPrice = 1 * product.Price;
                cartline.Name = product.Name;
                cart = _cartLineService.AddToCart(cart, cartline);
                SaveCart(cart);

                return cart.Count();
            }
            

        }
        public void SaveCart(List<CartLineViewModel> cart)
        {
            HttpContext.Session.SetJson("cart", cart);
        }
        public int DeleteFromCart(int id)
        {
            cart = TakeCart();
            cart = _cartLineService.DeleteInCart(cart, id);
            SaveCart(cart);
            return cart.Count();

        }
        public void DeleteCart()
        {
            //HttpContext.Session.Clear();    //Oturumda bulunan tüm session'ları siler.
            HttpContext.Session.Remove("cart"); //sadece ismi belirtilen session'ı siler.

        }
        // Sepet işlemleri

        //ürünü arttır
        public void IncreaseProduct(int id)
        {
            if (id != 0)
            {
                List<CartLineViewModel> cart = TakeCart();
                var ob = cart.Where(x => x.ProductId == id).FirstOrDefault();
                int stock = _productService.GetById(id).Stock;

                if (cart != null && stock - ob.Quantity > 0)
                {
                    ob.Quantity += 1;
                    ob.TotalPrice = ob.UnitPrice * ob.Quantity;
                }

                SaveCart(cart);

            }
        }
        //ürünü azalt
        public void DecreaseProduct(int id)
        {
            if (id != 0)
            {


                List<CartLineViewModel> cart = TakeCart();
                var ob = cart.Where(x => x.ProductId == id).FirstOrDefault();


                ob.Quantity -= 1;
                if (ob.Quantity == 0)
                {
                    DeleteFromCart(id);

                }
                else
                {
                    SaveCart(cart);
                }
            }

        }

        public IActionResult UpdatedCart()
        {
            var cart = HttpContext.Session.GetJson<List<CartLineViewModel>>("cart") ?? new List<CartLineViewModel>();
            return PartialView("_CartPartialView", cart);
        }








        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Payment(PrivateLessonBuyViewModel? Pmodel, int id)
        {
            PaymentViewModel model = new PaymentViewModel();

            //Salon üyeliği işlemleri (paket no larına göre buraya girebilir)
            //**************************************************************************************************
            if (id != 0) //paket satın alma işlemi için
            {

                var package = _packageService.GetPackagesById(id);
                model.Name = package.Name;
                model.Price = package.Price;
                model.PackageId = package.Id;
                model.Type = "package";
            }

            //Özel ders işlemleri için
            //***************************************************************************************************
            else if (Pmodel.TrainerId != 0)
            {
                var trainer = await _lessonService.GetLessonByTrainer(Pmodel.TrainerId, Pmodel.date);
                model.Price = trainer.TrainerPrice;
                model.Name = Pmodel.date.ToShortDateString() + " - Tarihinde Özel Ders Eğitmen : " + trainer.TrainerName;
                model.TrainerId = Pmodel.TrainerId;
                model.Type = "lesson";
                model.Day = Pmodel.date;
            }
            //Sepet işlemleri için
            //***************************************************************************************************
            else if (id == 0)
            {
                cart = TakeCart();
                model.Price = cart.Sum(x => x.TotalPrice);
                model.Name = "Alış Veriş";
                model.Type = "cart";
            }

            //Kullanıcının cüzdan bilgileri için
            //*****************************************************************************************************
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);   //oturum açmış olan kullanıcının Id si bulunur
            var wallet = await _walletService.GetUserWallet(Convert.ToInt32(userId)); //Id ye ait cüzdan bulunur
            model.Balance = wallet.Balance;
            model.WalletId = wallet.Id;
            model.UserId = Convert.ToInt32(userId);
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Payment(PaymentViewModel model)
        {
            //Bakiye kontrolü
            //**********************************************************************************
            if (model.Balance < model.Price)
            {
                ModelState.AddModelError("", "Lütfen Hesabınıza Para Yüklenmesi Yapın");
                return View(model);
            }
            //Paket işlemleri
            //*****************************************************************************
            if (model.Type == "package")
            {
                string message = await _accountService.UserAddPackage(model);
                if (message == "no")
                {

                    ModelState.AddModelError("", "Aktif Bir Üyeliğiniz Bulunmakta");
                    return RedirectToAction("StudentOrTrainer", "UserPage");
                }
            }
            //Özel ders işlemleri
            //**************************************************************************
            else if (model.Type == "lesson")
            {
                await _lessonService.UpdateLessonByTrainer(model);
                return RedirectToAction("StudentOrTrainer", "UserPage");
            }
            else if (model.Type == "cart")
            {
                cart = TakeCart();
                int cartId = await _cartService.CreateCart(model.UserId, cart.Sum(x => x.TotalPrice));
                _cartLineService.CreateCartLine(cart, cartId);
                await _productService.UpdateStock(cart);
                DeleteCart();
                return RedirectToAction("StudentOrTrainer", "UserPage");


            }


            //Cüzdan hareketi ekleme
            WalletDetailViewModel walletDetail = new WalletDetailViewModel()
            {
                ActivityDate = DateTime.Now,
                WalletId = model.WalletId,
                ActivityType = "Harcama",
                Amount = model.Price
            };
            await _walletDetailService.AddDetailToWallet(walletDetail);

FitMax.Mvc/Controllers/ContactController.cs
using FitMax.Entity.IService;
using FitMax.Entity.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FitMax.Mvc.Controllers
{
	public class ContactController : Controller
	{
		private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
        public async Task<IActionResult> Index(ContactViewModel model)
        {
          await  _contactService.SendMail(model);
			return RedirectToAction("Index", "Home");
        }
    }
}

FitMax.Mvc/Controllers/ProductsController.cs
using FitMax.Entity.IService;
using Microsoft.AspNetCore.Mvc;

namespace FitMax.Mvc.Controllers
{
	public class ProductsController : Controller
	{
		private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        public  async Task<IActionResult> Index(string search)
		{
            if (search!=null)
            {
                var models = await _productService.Search(search);
                return PartialView("_ProductsPartialView", models);
            }          
                var model = await _productService.GetAllTrue();
            
			return View(model);
		}
        public async Task<IActionResult> Filter(string filter)
        {
            var model = await _productService.GetAllByCategory(filter);


            return PartialView("_ProductsPartialView", model);
        }
     


    }
}

FitMax.Mvc/Controllers/TrainerPageController.cs
using FitMax.Entity.IService;
using FitMax.Entity.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Security.Claims;

namespace FitMax.Mvc.Controllers
{
    public class TrainerPageController : Controller
    {
        private readonly IPrivateLessonService _lessonService;
        private readonly IAccountService _accountService;

		public TrainerPageController(IPrivateLessonService lessonService, IAccountService accountService)
		{
			_lessonService = lessonService;
			_accountService = accountService;
		}
		[HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            ViewBag.trainer = _accountService.GetTrainerByd(id);          
            return View(await _lessonService.GetAllLessonsByTrainer(id));  //eğitmen sayfasına eğitmenin takvimi gönderilir
        }
        [HttpGet]
        public IActionResult BuyLesson(int id,string date)
        {
            PrivateLessonBuyViewModel model = new PrivateLessonBuyViewModel()
            {
                date = Convert.ToDateTime(date),
                TrainerId = id
            };
            return  RedirectToAction("Payment", "Cart", model);  //ödeme ekranına seçilen gün ve eğitmen bilgisi gönderilir

           

        }
    }
}

FitMax.Mvc/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Admin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/Admin/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/Admin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/Admin/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
                <a class="sidebar-brand brand-logo" style="text-decoration:none" href="/AdminHome/Index">FitMax</a>
                <a class="sidebar-brand brand-logo-mini" style="text-decoration:none" href="/AdminHome/Index">Fit</a>
            </div>
            <ul class="nav">
                <li class="nav-item profile">
                    <div class="profile-desc">
                        <div class="profile-pic">
                            <div class="count-indicator">
                                <i class="mdi mdi-account-card-details text-warning"></i>
                                <span class="count bg-success"></span>
                            </div>
                            <div class="profile-name">
                                <h5 class="mb-0 font-weight-normal">@User.Identity.Name</h5>

                            </div>
                        </div>
                        <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                        <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">

                            <div class="dropdown-divider"></div>
                            <a href="/Home/Index" class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-dark rounded-circle">
                                        <i class="mdi mdi-arrange-send-backward text-info"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <p class="preview-subject ellipsis mb-1 text-small">Siteye Git</p>
                                </div>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a asp-action="LogOut" asp-controller="Account" class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-dark rounded-circle">
                                        <i class="mdi mdi-exit-to-app text-success"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <p class="preview-subject ellipsis mb-1 text-small">Oturumu Kapat</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>

                <li class="nav-item nav-category">
                    <span class="nav-link">Menü</span>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-controller="AdminHome" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-speedometer"></i>
                        </span>
                        <span class="menu-title">Anasafya</span>
                    </a>
                </li>
               
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-controller="Trainer" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-owl"></i>
                        </span>
                        <span class="menu-title">Eğitmenler</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-controller="AdminUser" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-account-multiple-outline"></i>
                        </span>
                        <span class="menu-title">Üyeler</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-controller="AdminProduct" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-credit-card-scan"></i>
                        </span>
                        <span class="menu-title">Ürünler</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-action="Delivery" asp-controller="AdminProduct">
                        <span class="menu-icon">
                            <i class="mdi  mdi-arrow-up-bold-hexagon-outline"></i>
                        </span>
                        <span class="menu-title">Siparişler</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-action="Index" asp-controller="AdminPackage">
                        <span class="menu-icon">
                            <i class=" mdi mdi-dumbbell"></i>
                        </span>
                        <span class="menu-title">Salon Paketleri</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-action="Index" asp-controller="AdminRole">
                        <span class="menu-icon">
                            <i class="mdi mdi-lock-open-outline"></i>
                        </span>
                        <span class="menu-title">Yetkiler</span>
                    </a>
                </li>
           
               
               
            </ul>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            <nav class="navbar p-0 fixed-top d-flex flex-row">
                <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
                    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="assets/images/logo-mini.svg" alt="logo" /></a>
                </div>
                <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-menu"></span>
                    </button>
                   
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                        <span class="mdi mdi-format-line-spacing"></span>
                    </button>
                </div>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
        
                </div>
            </div>
            <!-- main-panel ends -->
            <!-- partial:partials/_footer.html -->
           
            <!-- partial -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Admin/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/Admin/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/Admin/assets/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/Admin/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="~/Admin/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/Admin/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Admin/assets/js/off-canvas.js"></script>
    <script src="~/Admin/assets/js/hoverable-collapse.js"></script>
    <script src="~/Admin/assets/js/misc.js"></script>
    <script src="~/Admin/assets/js/settings.js"></script>
    <script src="~/Admin/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/Admin/assets/js/dashboard.js"></script>
    <!-- End custom js for this page -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FitMax.Mvc/Views/Shared/_AdminProductPartialView.cshtml
<table class="table table-striped" id="products">
    <thead>
        <tr>
            <th> Adı </th>

            <th> Alış Fiyatı </th>
            <th> Satış Fiyatı </th>
            <th> Stok </th>
            <th> Durumu </th>
            <th> Detaylar </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>

                <td>
                    @item.Purchaseprice
                </td>
                <td>
                    @item.Price
                </td>
                <td>@item.Stock </td>
                <td><a class="btn btn-outline-@(item.Status == true ? "success" : "danger")">@(item.Status == true ? "Satışta" : "Satışa Kapalı")</a></td>
                <td><a asp-action="Details" asp-controller="AdminProduct" class="btn btn-primary" asp-route-id="@item.Id">Detaylar</a> </td>
                <td><a class="btn btn-outline-danger" onclick="deletep('@item.Id')">Ürün Sil</a> </td>
            </tr>
        }
      
    </tbody>
</table>

FitMax.Mvc/Views/Shared/_DeliveryPartialView.cshtml
@model IEnumerable<CartLineViewModel>



<table class="table table-striped" id="Table">
    <thead>
        <tr>

            <th> Urun </th>
            <th> Adet </th>
            <th> Sipariş Tarihi </th>
            <th> Teslim Tarihi </th>
            <th> Durumu </th>
        </tr>
    </thead>
    <tbody>
        @{
            int totatlQuantity = 0;
            decimal totalPrice = 0;
        }
        @foreach (var Model in Model)
        {


            <tr>
                <td> @Model.Product.Name </td>
                <td> @Model.Quantity </td>
                <td> @Model.OrderDate </td>
                <td> @Model.DeliveryDate </td>
                <td> <a class="btn btn-outline-@(Model.Status==true?"success":"danger")">@(Model.Status == true ? "Teslim Edildi" : "Teslim Edlimedi")</a> </td>
                <td>
                    @if (Model.Status == false)
                    {
                        <a class="btn btn-success" onclick="deliveryto('@Model.Id','@Model.CartId')">Teslim Et</a>
                    }
                </td>
                @{
                    totatlQuantity += Model.Quantity;
                    totalPrice += Model.TotalPrice;
                }

            </tr>
        }
        <h3 style="color:gray">Sepet Toplamı : @totalPrice.ToString("C")</h3>
        <h5 style="color:gray">Toplam Ürün Adeti : @totatlQuantity</h5>
    </tbody>


</table>

FitMax.Mvc/Views/Shared/_FooterPartialView.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-3 footer-item-logo">
                <a href="index-2.html" class="logo-footer"><img src="~/fitmax/assets/img/footer-logo2.svg" alt="logo"></a>
                <p>Sağlıklı ve güçlü bir yaşam için buradayız.</p>
           
            </div>
            <div class="col-sm-6 col-lg-3 footer-item footer-item-list">
                <h3>Linkler</h3>
                <ul class="footer-link">
                    <li><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                    <li><a asp-controller="Products" asp-action="Index">Ürünler</a></li>
                    <li><a asp-controller="Contact" asp-action="Index">İletişim</a></li>
                    <li><a asp-controller="Account" asp-action="Login">Giriş</a></li>
                    <li><a asp-controller="Account" asp-action="Register">Üyelik</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3 footer-item">
                <h3>Bizimle İletişime Geçin</h3>
                <ul class="footer-cont">
                    <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:18004886040">1-800-488-6040</a></li>
                    <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:crossFit@gmail.com">CrossFit@gmail.com</a></li>
                    <li><i class="fa fa-map-marker" aria-hidden="true"></i><a href="contacts.html">İstanbul/Türkiye</a></li>
                    <li><a target="_blank" href="https://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a></li>
                    <li><a target="_blank" href="https://twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a></li>
                    <li><a target="_blank" href="https://www.youtube.com"><i class="fa fa-youtube" aria-hidden="true"></i>Youtube</a></li>
                    <li><a target="_blank" href="https://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i>İnstagram</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3 footer-item">
                <h3>Çalışma Saatleri</h3>
                <ul class="footer-blog">         
                    <li><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;&nbsp; Tüm Hafta: 08:00 - 22:00</li>
                    
                </ul>
            </div>
        </div>
        
    </div>
</footer>

FitMax.Mvc/Views/Shared/_TrainercalendarPartialView.cshtml
@model IEnumerable<PrivateLessonViewModel>
@if (Model.Count()==0)
{
    <div style="text-align:center">
        <h2>Henüz Özel Ders Yok</h2>
    </div>
}
else
{


    <section class="s-training-schedule" style="background-image: url(/fitmax/ssets/img/bg-table-1.svg);margin-top:-300px">
        <div class="container">
            <h2 class="title-decor">Eğitmen <span>Takvimi</span></h2>
            <p class="slogan">Eğitmenden istediğiniz boş günü için ders randevusu alabilirsiniz. Ders iptalleri için lütfen yönetimle iletişime geçiniz.</p>
            <div class="training-schedule-cover">
                <div style="text-align: center;">
                    <h3 class="training-schedule-top ">@Model.FirstOrDefault().TrainerName</h3>
                    <h3 class="training-schedule-top d-inline-block" style="font-size:13px">Günlük Ders Ücreti :  @Model.FirstOrDefault().TrainerPrice.ToString("C")</h3>
                </div>
                <div class="training-schedule-table">

                    <table>
                        <thead>
                            <tr>

                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>

                            <tr>
                                @{
                                    int a = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    a++;
                                    if (a==8)
                                    {
                                        break;
                                    }
                                    <td>
                                        @item.Date.ToString("dd-MM-yyyy")
                                        @if (item.Lesson == "empty")
                                        {

                                            <a asp-action="BuyLesson" asp-controller="TrainerPage" asp-route-id="@item.TrainerId" asp-route-date="@item.Date.ToShortDateString()" class="btn">SEÇ</a>
                                        }
                                        else
                                        {
                                            <div class="name"><a class="btn">DOlU</a></div>
                                        }


                                    </td>

                                }
                            </tr>
                            <tr>                              
                                @foreach (var item in Model.Skip(7))
                                {                                   
                                    <td>
                                        @item.Date.ToString("dd-MM-yyyy")
                                        @if (item.Lesson == "empty")
                                        {

                                            <a asp-action="BuyLesson" asp-controller="TrainerPage" asp-route-id="@item.TrainerId" asp-route-date="@item.Date.ToShortDateString()" class="btn">SEÇ</a>
                                        }
                                        else
                                        {
                                            <div class="name"><a class="btn">DOlU</a></div>
                                        }


                                    </td>

                                }
                            </tr>

                        </tbody>

                    </table>

                </div>
            </div>
        </div>
    </section>
}