FitMax.Mvc/Controllers/Admin/AdminContactController.cs
using FitMax.Entity.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitMax.Mvc.Controllers.Admin
{
    [Authorize(Roles ="Admin")]
    public class AdminContactController : Controller
    {
        private readonly IContactService _contactService;

        public AdminContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public async Task<IActionResult> Index(int id)
        {
            return View(await _contactService.GEtMailById(id));
        }

    }
}

FitMax.Mvc/ViewComponents/AdminEmails/AdminEmailsViewComponent.cs
using FitMax.Entity.IService;
using Microsoft.AspNetCore.Mvc;

namespace FitMax.Mvc.ViewComponents.AdminEmails
{
    public class AdminEmailsViewComponent : ViewComponent
    {
        private readonly IContactService _contactService;

        public AdminEmailsViewComponent(IContactService contactService)
        {
            _contactService = contactService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        { 
            return View(await _contactService.GetAllMail());
        }
    }
}

FitMax.Mvc/Views/Shared/Components/AdminEmails/Default.cshtml
@model IEnumerable<ContactViewModel>
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mailler</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>

                                <th> Göderen </th>                                
                                <th> Mail </th>
                                <th> Tarih </th>
                                <th> Durum </th>
                                <th> Detaylar </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>

                                    <td>@item.Name </td>
                                    <td>@item.Email </td>
                                    <td> @item.Date </td>
                                    <td style="color:@(@item.IsReaded == true ? "green" : "red")">@(@item.IsReaded == true ? "Okundu" : "Okunmadı")</td>
                                    <td> <a asp-controller="AdminContact" asp-action="Index" asp-route-id="@item.Id" class="btn btn-success">Detaylar</a> </td>


                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>